import { Arima } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import ContextProvider from '@/context/ContextProvider';
import { ToastContainer } from 'react-toastify';

const arima = Arima({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full antialiased`}
    >
      <body className={`${arima.className} bg-base-300 min-h-screen text-base-content`}>
        <Navbar />
        <ContextProvider>
          {children}
        </ContextProvider>
        <Footer />
        <ToastContainer position="top-left"/>
      </body>
    </html>
  );
}
